events { }

http {
    upstream coordinator_cluster {
        least_conn;
        server coordinator-service-1:5000;
        server coordinator-service-2:5000;
    }

    upstream id_cluster {
        least_conn;
        server id-service-1:8000;
        server id-service-2:8000;
        server id-service-3:8000;
        server id-service-4:8000;
    }

    server {
        listen 5000;
        location / {
            proxy_pass http://coordinator_cluster;
        }
    }

    server {
        listen 8000;
        location / {
            proxy_pass http://id_cluster;
        }
    }
}
